game/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^$', 'game.views.index', name='index'),
    url(r'^create_game/', 'game.views.create_game', name='create_game'),
    url(r'^my_games/', 'game.views.my_games', name='my_games'),
    url(r'^edit_game/(?P<game_id>\d+)/$', 'game.views.edit_game', name='edit_game'),

)

kids_football/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from registration.forms import RegistrationFormUniqueEmail


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('game.urls')),
    url(r'^profile/', include('user_profile.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, {'next_page': '/'}, name='logout'),

    # url(r'^register/$', RegistrationFormUniqueEmail.as_view(), name='registration_register'),
    # url(r'^register/$', 'registration.views.register', {'form': RegistrationFormUniqueEmail}, name='registration_register'),

    # url('', include('registration.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    # url(r'^accounts/', include('registration.urls')),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/models.py
# -*- coding: utf-8 -*-
from django.db import models
from user_profile.models import Profile


AGE = (('a5a7', 'от 5 до 7'),
       ('a7a9', 'от 7 до 9'),
       ('a9a11', 'от 9 до 11'),
       ('a11a13', 'от 11 до 13'),
       ('a13a15', 'от 13 до 15'),)

TYPES = (('friend', 'товарищеская игра'),
         ('tournament', 'турнир'),
         ('training', 'тренировка'),)


class Game(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название')
    slug = models.SlugField(max_length=250)
    team_creator = models.CharField(max_length=250)
    team_accepted = models.CharField(max_length=250, blank=True, null=True)
    date_time_start = models.DateTimeField(verbose_name='Дата, время начала')
    type = models.CharField(max_length=15, choices=TYPES,
                            verbose_name='Тип игры')
    location = models.TextField(verbose_name='Где будем играть')
    duration = models.CharField(max_length=250, verbose_name='Длительность')
    age = models.CharField(max_length=6, choices=AGE,
                           verbose_name='Возрастная категория')
    creator = models.ForeignKey(Profile)
    winner = models.NullBooleanField(blank=True, null=True)
    score = models.CharField(max_length=20, blank=True, null=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = 'игра'
        verbose_name_plural = 'игры'

game/forms.py
# -*- coding: utf-8 -*-
from django import forms
from game.models import Game

from kids_football.widgets import DateTimePickerWidget


class CreateGameForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CreateGameForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Game
        fields = ['title', 'date_time_start', 'type', 'location', 'duration', 'age']
        widgets = {
            'date_time_start': DateTimePickerWidget()
        }

game/views.py
import json
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.paginator import Paginator

from game.models import Game
from user_profile.models import Profile
from game.forms import CreateGameForm


def index(request, page=1):
    try:
        user = request.user
        profile, created = Profile.objects.get_or_create(user=user)
    except TypeError:
        profile = None
    games = Paginator(Game.objects.all().select_related('creator__user'), 5)
    return render(request, 'game/index.html',
                  {'games': games.page(page),
                   'profile': profile})


@login_required
def create_game(request):
    response = {}
    user = request.user
    profile, create = Profile.objects.get_or_create(user=user)
    if request.POST:
        create_game_form = CreateGameForm(request.POST)
        if create_game_form.is_valid():
            game = create_game_form.save(commit=False)
            game.team_creator = profile.team
            game.creator = profile
            game.save()
            response['success'] = 'true'
            return HttpResponse(json.dumps(response),
                                content_type='application/json')
        else:
            if create_game_form.errors:
                errs = {}
                for error in create_game_form.errors:
                    e = create_game_form.errors[error]
                    errs[error] = unicode(e)
                response['success'] = 'false'
                response['errors'] = errs
            return HttpResponse(json.dumps(response),
                                content_type='application/json')
    return render(request, 'game/create_game.html',
                  {'create_game_form': CreateGameForm(),
                   'profile': profile})


@login_required
def edit_game(request, game_id):
    user = request.user
    game = Game.objects.select_related('creator').get(id=game_id)
    if user == game.creator.user:
        profile = Profile.objects.get(user=user)
        response = {}
        if request.POST and request.is_ajax():
            edit_game_form = CreateGameForm(request.POST, instance=game)
            if edit_game_form.is_valid():
                edit_game_form.save()
                response['success'] = 'true'
                return HttpResponse(json.dumps(response),
                                    content_type='application/json')
            else:
                if edit_game_form.errors:
                    errs = {}
                    for error in edit_game_form.errors:
                        e = edit_game_form.errors[error]
                        errs[error] = unicode(e)
                    response['success'] = 'false'
                    response['errors'] = errs
                return HttpResponse(json.dumps(response),
                                    content_type='application/json')
        return render(request, 'game/edit_game.html',
                      {'edit_game_form': CreateGameForm(instance=game),
                       'profile': profile,
                       'game': game})
    else:
        return render(request, 'game/edit_game.html',
                      {'access_denied': 'access_denied'})



@login_required
def my_games(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    games = Game.objects.all().select_related('creator__user').filter(creator=profile)
    return render(request, 'game/index.html',
                  {'games': games,
                   'profile': profile})

templates/game/create_game.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Страница создания игры{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" media="screen, projection"/>
    <script type="text/javascript" src="{% static 'js/moment-with-locales.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/transition.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/collapse.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.form.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/create_game.js' %}"></script>
    {{ form.media }}
{% endblock extra_head %}

{% block content %}
    <h1 class="text-center">Создать игру</h1>
    {% if user.is_authenticated %}
    <div class="container">
        {% if profile.team %}
            <form action="{% url 'create_game' %}" method="post" enctype="multipart/form-data" id="editform">
                {% csrf_token %}
                {{ create_game_form.non_field_errors }}
                <div class="row">
                    <div class="col-md-10">
                        <div class="main">
                            <div class="field">
                                <p>
                                    {{ create_game_form.title.errors }}
                                    <label for="{{ create_game_form.title.id_for_label }}">Название:</label>
                                    {{ create_game_form.title }}
                                </p>
                                <p>
                                    {{ create_game_form.date_time_start.errors }}
                                    <label for="{{ create_game_form.date_time_start.id_for_label }}">Дата, время начала:</label>
                                    {{ create_game_form.date_time_start }}
                                </p>
                                <p>
                                    {{ create_game_form.type.errors }}
                                    <label for="{{ create_game_form.type.id_for_label }}">Тип игры:</label>
                                    {{ create_game_form.type }}
                                </p>
                                <p>
                                    {{ create_game_form.location.errors }}
                                    <label for="{{ create_game_form.location.id_for_label }}">Где будем играть:</label>
                                    {{ create_game_form.location }}
                                </p>
                                <p>
                                    {{ create_game_form.duration.errors }}
                                    <label for="{{ create_game_form.duration.id_for_label }}">Длительность:</label>
                                    {{ create_game_form.duration }}
                                </p>
                                <p>
                                    {{ create_game_form.age.errors }}
                                    <label for="{{ create_game_form.age.id_for_label }}">Возрастная категория:</label>
                                    {{ create_game_form.age }}
                                </p>
                            </div>
                        </div>
                    </div>
                    {% include 'right.html' %}
                </div>
                <br>
                <div id="loading">
                    <img src="{% static 'img/loading.gif' %}">
                </div>
                <div id="form_ajax">
                    <span>Game have been created.</span>
                </div>
                <div id="form_ajax_error">
                    <span>Can not submit data due to errors.</span>
                </div>
                <input type="submit" value="Создать" class="btn btn-primary" id="sendbutton"/>
                <input type="hidden" name="next" value="/" />
                <a id="index" href="{% url 'index' %}">Cancel</a>
                <br>
                <br>
                <br>
            </form>
        {% else %}
            <p>Вы должны присоединиться к команде прежде чем создавать игру <a href="{% url 'edit_profile' %}">Присоединиться</a></p>
        {% endif %}
    </div>
    {% endif %}
{% endblock %}

templates/game/edit_game.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Редактирование игры{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" media="screen, projection"/>
    <script type="text/javascript" src="{% static 'js/moment-with-locales.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/transition.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/collapse.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.form.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/create_game.js' %}"></script>
    {{ form.media }}
{% endblock extra_head %}

{% block content %}
    {% if access_denied != 'access_denied' %}
        <h1 class="text-center">Редактировать игру</h1>
        {% if user.is_authenticated %}
        <div class="container">
            <form action="{% url 'edit_game' game.id  %}" method="post" enctype="multipart/form-data" id="editform">
                {% csrf_token %}
                {{ edit_game_form.non_field_errors }}
                <div class="row">
                    <div class="col-md-10">
                        <div class="main">
                            <div class="field">
                                <p>
                                    {{ edit_game_form.title.errors }}
                                    <label for="{{ edit_game_form.title.id_for_label }}">Название:</label>
                                    {{ edit_game_form.title }}
                                </p>
                                <p>
                                    {{ edit_game_form.date_time_start.errors }}
                                    <label for="{{ edit_game_form.date_time_start.id_for_label }}">Дата, время начала:</label>
                                    {{ edit_game_form.date_time_start }}
                                </p>
                                <p>
                                    {{ edit_game_form.type.errors }}
                                    <label for="{{ edit_game_form.type.id_for_label }}">Тип игры:</label>
                                    {{ edit_game_form.type }}
                                </p>
                                <p>
                                    {{ edit_game_form.location.errors }}
                                    <label for="{{ edit_game_form.location.id_for_label }}">Где будем играть:</label>
                                    {{ edit_game_form.location }}
                                </p>
                                <p>
                                    {{ edit_game_form.duration.errors }}
                                    <label for="{{ edit_game_form.duration.id_for_label }}">Длительность:</label>
                                    {{ edit_game_form.duration }}
                                </p>
                                <p>
                                    {{ edit_game_form.age.errors }}
                                    <label for="{{ edit_game_form.age.id_for_label }}">Возрастная категория:</label>
                                    {{ edit_game_form.age }}
                                </p>
                            </div>
                        </div>
                    </div>
                    {% include 'right.html' %}
                </div>
                <br>
                <div id="loading">
                    <img src="{% static 'img/loading.gif' %}">
                </div>
                <div id="form_ajax">
                    <span>Game have been created.</span>
                </div>
                <div id="form_ajax_error">
                    <span>Can not submit data due to errors.</span>
                </div>
                <input type="submit" value="Редактировать" class="btn btn-primary" id="sendbutton"/>
                <input type="hidden" name="next" value="/" />
                <a id="index" href="{% url 'index' %}">Cancel</a>
                <br>
                <br>
                <br>
            </form>
        </div>
        {% endif %}
    {% else %}
        <div class="container">Вы можете редактировать только игры созданные Вами. <a href="{% url 'my_games' %}">Мои игры</a></div>
    {% endif %}
{% endblock %}

templates/game/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
        <h1 class="text-center">TEST</h1>
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <br>
                    {% for game in games %}
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div>Название игры: {{ game.title }}</div>
                                        <div>Вызов бросила команды: {{ game.team_creator }}</div>
                                        {% if game.team_accepted %}
                                            <div>Вызов приняла команда: {{ game.team_accepted }}</div>
                                        {% else %}
                                            <div>Вызов приняла команда: Вызов пока не принят</div>
                                        {% endif %}
                                        <div>Дата и время начала: {{ game.date_time_start }}</div>
                                        <div>Тип игры: {{ game.get_type_display }}</div>
                                    </div>
                                    <div class="col-md-6">
                                        <div>Где будут играть: {{ game.location|linebreaks }}</div>
                                        <div>Длительность: {{ game.duration }}</div>
                                        <div>Возрастная категория: {{ game.get_age_display }}</div>
                                        {% if game.winner == None %}
                                            <div>Победитель: скоро определится</div>
                                        {% else %}
                                            <div>Победитель: {{ game.winner }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% if user.is_authenticated %}
                                <div class="panel-footer">
                                {% if user != game.creator.user %}
                                    <a class="btn btn-primary" href="#">Принять вызов</a>
                                {% else %}
                                    <a class="btn btn-primary" href="{% url 'edit_game' game.id %}">Редактировать</a>
                                {% endif %}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                    {% include 'right.html' %}
            </div>
        </div>
{% endblock content %}